{% set name = "xroms" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xroms-{{ version }}.tar.gz
  sha256: ede2f4bda2e2283683b48a99e7d7721c045f924ddf8d4b6630a15dc8022702e1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6
    - cf_xarray
    - dask-core
    - netcdf4
    - numba >=0.49
    - numpy
    - pooch
    - xarray
    - xgcm >=0.8.1

test:
  imports:
    - xroms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xoceanmodel/xroms
  summary: Package for working with ROMS output in xarray
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
