{% set name = "xroms" %}
{% set version = "0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xroms-{{ version }}.tar.gz
  sha256: 671e0766ddba21978b26bdf32d0aafdeb9dbc128d8c6d58a193825bb1a420a4d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - setuptools >=42
    - wheel
    - setuptools-scm >=3.4
    - pip
  run:
    - python >=3.6
    - cf_xarray
    - dask-core
    - netcdf4
    - numba >=0.49
    - numpy
    - pooch
    - xarray
    - xgcm >=0.8.1

test:
  imports:
    - xroms
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/xoceanmodel/xroms
  summary: Package for working with ROMS output in xarray
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kthyng
